### ISSUE TITLE
[CRITICAL] Roblox update broke?

### ISSUE THREAD

**Issue by TheLegendarySpark** [Hexcede/H6x#20]
**Describe the bug**
This error has popped up unexpectedly and was reported by one of my users.

**To Reproduce**
1. Run security test
![image](https://user-images.githubusercontent.com/39038022/180915784-7d0dca07-e695-4691-b972-486b84a6cb47.png)

**Version information (please complete the following information):**
 - H6x version: 2.1.1
 - Beta features enabled: Parallel Lua

**Comment by Hexcede** [comment]
Can reproduce.

**Comment by Hexcede** [comment]
@TheLegendarySpark Could you provide the time that they reported the issue? Would help when making a report to Roblox. I'm currently attempting to determine the root cause.

**Comment by Hexcede** [comment]
Actually, nevermind. I've determined the source of the issue. It's a result of the len metamethod now applying to tables. About to push hotfix `2.1.2`.

**Comment by Hexcede** [comment]
This is now fixed in `2.1.2`. Update your wally manifest if you're using one or update H6x.
